export const diagnosisColumns = {
    'local': [
        {
            "field": "id",
            "headerName": "진단코드",
            "disableReorder": true,
            "disableColumnMenu": true,
            "flex": 1,
        },
        {
            "field": "medical_institution",
            "headerName": "의료기관",
            "disableReorder": true,
            "disableColumnMenu": true,
            "width": 96,
        },
        {
            "field": "local_label",
            "headerName": "진단명",
            "disableReorder": true,
            "disableColumnMenu": true,
            "flex": 1,
        },
        {
            "field": "snomed_ct_code",
            "headerName": "SNOMED CT 코드",
            "disableReorder": true,
            "disableColumnMenu": true,
            "flex": 1,
        },
        {
            "field": "snomed_ct_label",
            "headerName": "SNOMED CT 명",
            "disableReorder": true,
            "disableColumnMenu": true,
            "flex": 1,
        },
        {
            "field": "kcd8_code",
            "headerName": "KCT8 코드",
            "disableReorder": true,
            "disableColumnMenu": true,
            "flex": 1,
        },
        {
            "field": "kcd8_label",
            "headerName": "KCT8 코드명",
            "disableReorder": true,
            "disableColumnMenu": true,
            "flex": 1,
        },
    ],
}

export const diagnosisRows = {
    'local': [
        {
            id: "D00000001",
            medical_institution: "공통",
            local_label: "Cholera due to Vibrio cholerae O1, classical",
            snomed_ct_code: "240349003",
            snomed_ct_label: "Cholera caused by Vibrio cholerae O1 Classical biotype (disorder)",
            kcd8_code: "A000",
            kcd8_label: "비브리오 콜레라 01 콜레라형균에 의한 콜레라",
        },
        {
            id: "D00000002",
            medical_institution: "공통",
            local_label: "Cholera due to Vibrio cholerae O1, El Tor",
            snomed_ct_code: "81020007",
            snomed_ct_label: "Cholera caused by Vibrio cholerae El Tor (disorder)",
            kcd8_code: "A001",
            kcd8_label: "비브리오 콜레라 01 엘토르형균에 의한 콜레라",
        },
        {
            id: "D00000003",
            medical_institution: "공통",
            local_label: "Cholera",
            snomed_ct_code: "63650001",
            snomed_ct_label: "Cholera (disorder)",
            kcd8_code: "A009",
            kcd8_label: "상세불명의 콜레라",
        },
        {
            id: "D00000004",
            medical_institution: "공통",
            local_label: "Typhoid fever",
            snomed_ct_code: "4834000",
            snomed_ct_label: "Typhoid fever (disorder)",
            kcd8_code: "A010",
            kcd8_label: "장티푸스",
        },
        {
            id: "D00000005",
            medical_institution: "공통",
            local_label: "Paratyphoid fever A",
            snomed_ct_code: "76623002",
            snomed_ct_label: "Paratyphoid A fever (disorder)",
            kcd8_code: "A011",
            kcd8_label: "파라티푸스 A",
        },
        {
            id: "D00000006",
            medical_institution: "공통",
            local_label: "Paratyphoid fever B",
            snomed_ct_code: "71085009",
            snomed_ct_label: "Paratyphoid B fever (disorder)",
            kcd8_code: "A012",
            kcd8_label: "파라티푸스 B",
        },
        {
            id: "D00000007",
            medical_institution: "공통",
            local_label: "Paratyphoid fever C",
            snomed_ct_code: "51254007",
            snomed_ct_label: "Paratyphoid C fever (disorder)",
            kcd8_code: "A013",
            kcd8_label: "파라티푸스 C",
        },
        {
            id: "D00000008",
            medical_institution: "공통",
            local_label: "Paratyphoid fever",
            snomed_ct_code: "85904008",
            snomed_ct_label: "Paratyphoid fever (disorder)",
            kcd8_code: "A014",
            kcd8_label: "상세불명의 파라티푸스",
        },
        {
            id: "D00000009",
            medical_institution: "공통",
            local_label: "Salmonella enteritis",
            snomed_ct_code: "397503006",
            snomed_ct_label: "Salmonella enterica subspecies arizonae infection (disorder)",
            kcd8_code: "A020",
            kcd8_label: "살모넬라장염",
        },
        {
            id: "D00000010",
            medical_institution: "공통",
            local_label: "Salmonella sepsis",
            snomed_ct_code: "449083008",
            snomed_ct_label: "Sepsis caused by Salmonella (disorder)",
            kcd8_code: "A021",
            kcd8_label: "살모넬라패혈증",
        },
        {
            id: "D00000011",
            medical_institution: "공통",
            local_label: "Localized salmonella infection",
            snomed_ct_code: "47375003",
            snomed_ct_label: "Localized Salmonella infection (disorder)",
            kcd8_code: "A022",
            kcd8_label: "국소적 살모넬라감염",
        },
        {
            id: "D00000012",
            medical_institution: "공통",
            local_label: "Other specified salmonella infections",
            snomed_ct_code: "302231008",
            snomed_ct_label: "Salmonella infection (disorder)",
            kcd8_code: "A028",
            kcd8_label: "기타 명시된 살모넬라감염",
        },
        {
            id: "D00000014",
            medical_institution: "공통",
            local_label: "Salmonella infection",
            snomed_ct_code: "302231008",
            snomed_ct_label: "Salmonella infection (disorder)",
            kcd8_code: "A029",
            kcd8_label: "상세불명의 살모넬라감염",
        },
        {
            id: "D00000013",
            medical_institution: "공통",
            local_label: "Salmonella food poisoning",
            snomed_ct_code: "302229004",
            snomed_ct_label: "Salmonella food poisoning (disorder)",
            kcd8_code: "A029",
            kcd8_label: "상세불명의 살모넬라감염",
        },
        {
            id: "D00000015",
            medical_institution: "공통",
            local_label: "Shigellosis due to Shigella dysenteriae",
            snomed_ct_code: "66301008",
            snomed_ct_label: "Infection caused by Group A Shigella (disorder)",
            kcd8_code: "A030",
            kcd8_label: "이질이질균에 의한 시겔라증",
        },
        {
            id: "D00000016",
            medical_institution: "공통",
            local_label: "Shigellosis due to Shigella flexneri",
            snomed_ct_code: "34335000",
            snomed_ct_label: "Infection caused by Group B Shigella (disorder)",
            kcd8_code: "A031",
            kcd8_label: "플렉스네리이질균에 의한 시겔라증",
        },
        {
            id: "D00000017",
            medical_institution: "공통",
            local_label: "Shigellosis due to Shigella boydii",
            snomed_ct_code: "55760004",
            snomed_ct_label: "Infection caused by Group C Shigella (disorder)",
            kcd8_code: "A032",
            kcd8_label: "보이디이질균에 의한 시겔라증",
        },
        {
            id: "D00000018",
            medical_institution: "공통",
            local_label: "Shigellosis due to Shigella sonnei",
            snomed_ct_code: "69794009",
            snomed_ct_label: "Infection caused by Group D Shigella (disorder)",
            kcd8_code: "A033",
            kcd8_label: "소네이이질균에 의한 시겔라증",
        },
        {
            id: "D00000019",
            medical_institution: "공통",
            local_label: "Bacillary dysentery",
            snomed_ct_code: "274081004",
            snomed_ct_label: "Bacillary dysentery (disorder)",
            kcd8_code: "A039",
            kcd8_label: "상세불명의 시겔라증",
        },
        {
            id: "D00000020",
            medical_institution: "공통",
            local_label: "Shigellosis",
            snomed_ct_code: "36188001",
            snomed_ct_label: "Shigellosis (disorder)",
            kcd8_code: "A039",
            kcd8_label: "상세불명의 시겔라증",
        },
        {
            id: "D00000021",
            medical_institution: "공통",
            local_label: "Enteropathogenic Escherichia coli infection",
            snomed_ct_code: "240353001",
            snomed_ct_label: "Enteropathogenic Escherichia coli gastrointestinal tract infection (disorder)",
            kcd8_code: "A040",
            kcd8_label: "장병원성 대장균감염",
        },
        {
            id: "D00000022",
            medical_institution: "공통",
            local_label: "Enterotoxigenic Escherichia coli infection",
            snomed_ct_code: "240352006",
            snomed_ct_label: "Enterotoxigenic Escherichia coli gastrointestinal tract infection (disorder)",
            kcd8_code: "A041",
            kcd8_label: "장독소생산 대장균감염",
        },
        {
            id: "D00000023",
            medical_institution: "공통",
            local_label: "Enteroinvasive Escherichia coli infection",
            snomed_ct_code: "240355008",
            snomed_ct_label: "Enteroinvasive Escherichia coli gastrointestinal tract infection (disorder)",
            kcd8_code: "A042",
            kcd8_label: "장침투성 대장균감염",
        },
        {
            id: "D00000026",
            medical_institution: "공통",
            local_label: "Escherichia coli O157 infection",
            snomed_ct_code: "127531000119106",
            snomed_ct_label: "Infection caused by Escherichia coli O157 (disorder)",
            kcd8_code: "A043",
            kcd8_label: "장출혈성 대장균감염",
        },
        {
            id: "D00000024",
            medical_institution: "공통",
            local_label: "Enterohemorrhagic Escherichia coli infection",
            snomed_ct_code: "240354007",
            snomed_ct_label: "Verotoxigenic Escherichia coli gastrointestinal tract infection (disorder)",
            kcd8_code: "A043",
            kcd8_label: "장출혈성 대장균감염",
        },
        {
            id: "D00000025",
            medical_institution: "공통",
            local_label: "Escherichia coli infection",
            snomed_ct_code: "71057007",
            snomed_ct_label: "Infection caused by Escherichia coli (disorder)",
            kcd8_code: "A044",
            kcd8_label: "기타 장대장균감염",
        },
        {
            id: "D00000027",
            medical_institution: "공통",
            local_label: "Campylobacter enteritis",
            snomed_ct_code: "18081009",
            snomed_ct_label: "Enteric campylobacteriosis (disorder)",
            kcd8_code: "A045",
            kcd8_label: "캄필로박터장염",
        },
        {
            id: "D00000028",
            medical_institution: "공통",
            local_label: "Yersinia enterocolitica infection",
            snomed_ct_code: "80960004",
            snomed_ct_label: "Infection caused by Yersinia enterocolitica (disorder)",
            kcd8_code: "A046",
            kcd8_label: "예르시니아 엔테로콜리티카에 의한 장염",
        },
        {
            id: "D00000029",
            medical_institution: "공통",
            local_label: "Pseudomembranous colitis",
            snomed_ct_code: "423590009",
            snomed_ct_label: "Clostridium difficile colitis (disorder)",
            kcd8_code: "A047",
            kcd8_label: "클로스트리듐 디피실리에 의한 장결장염",
        },
        {
            id: "D00022674",
            medical_institution: "공통",
            local_label: "Food poisoning, Clostridium difficile intoxication",
            snomed_ct_code: "186431008",
            snomed_ct_label: "Infection caused by Clostridioides difficile (disorder)",
            kcd8_code: "A047",
            kcd8_label: "클로스트리듐 디피실리에 의한 장결장염",
        },
        {
            id: "D00000031",
            medical_institution: "공통",
            local_label: "Helicobacter infection",
            snomed_ct_code: "721730009",
            snomed_ct_label: "Infection caused by Helicobacter pylori (disorder)",
            kcd8_code: "A048",
            kcd8_label: "기타 명시된 세균성 장감염",
        },
        {
            id: "D00000030",
            medical_institution: "공통",
            local_label: "Diarrheogenic bacterial enteritis",
            snomed_ct_code: "75375008",
            snomed_ct_label: "Inflammation of intestine caused by bacteria (disorder)",
            kcd8_code: "A048",
            kcd8_label: "기타 명시된 세균성 장감염",
        },
        {
            id: "D00000032",
            medical_institution: "공통",
            local_label: "Bacterial enteritis",
            snomed_ct_code: "75375008",
            snomed_ct_label: "Inflammation of intestine caused by bacteria (disorder)",
            kcd8_code: "A049",
            kcd8_label: "상세불명의 세균성 장감염",
        },
        {
            id: "D00000033",
            medical_institution: "공통",
            local_label: "Staphylococcal food poisoning",
            snomed_ct_code: "84622004",
            snomed_ct_label: "Food poisoning caused by staphylococcus (disorder)",
            kcd8_code: "A050",
            kcd8_label: "음식매개포도알균중독",
        },
        {
            id: "D00000034",
            medical_institution: "공통",
            local_label: "Botulism",
            snomed_ct_code: "398565003",
            snomed_ct_label: "Infection caused by Clostridium botulinum (disorder)",
            kcd8_code: "A051",
            kcd8_label: "보틀리눔중독",
        },
        {
            id: "D00000035",
            medical_institution: "공통",
            local_label: "Food poisoning, Clostridium perfringens intoxication",
            snomed_ct_code: "70014009",
            snomed_ct_label: "Food poisoning caused by Clostridium perfringens (disorder)",
            kcd8_code: "A052",
            kcd8_label: "클로스트리듐 퍼프린젠스[클로스트리듐 웰치]에 의한 식중독",
        },
        {
            id: "D00000036",
            medical_institution: "공통",
            local_label: "Food poisoning, Vibrio parahaemolyticus intoxication",
            snomed_ct_code: "81159000",
            snomed_ct_label: "Food poisoning caused by Vibrio parahaemolyticus (disorder)",
            kcd8_code: "A053",
            kcd8_label: "장염비브리오균에 의한 식중독",
        },
        {
            id: "D00000037",
            medical_institution: "공통",
            local_label: "Food poisoning, Bacillus cereus intoxication",
            snomed_ct_code: "19894004",
            snomed_ct_label: "Food poisoning caused by Bacillus cereus (disorder)",
            kcd8_code: "A054",
            kcd8_label: "바실루스 세레우스에 의한 식중독",
        },
        {
            id: "D00000038",
            medical_institution: "공통",
            local_label: "Bacterial food poisoning",
            snomed_ct_code: "66107000",
            snomed_ct_label: "Bacterial food poisoning (disorder)",
            kcd8_code: "A059",
            kcd8_label: "상세불명의 세균성 식중독",
        },
        {
            id: "D00000039",
            medical_institution: "공통",
            local_label: "Acute amebic dysentery",
            snomed_ct_code: "186116005",
            snomed_ct_label: "Acute amebic dysentery (disorder)",
            kcd8_code: "A060",
            kcd8_label: "급성 아메바이질",
        },
        {
            id: "D00000040",
            medical_institution: "공통",
            local_label: "Chronic intestinal amebiasis",
            snomed_ct_code: "23874000",
            snomed_ct_label: "Chronic amebiasis (disorder)",
            kcd8_code: "A061",
            kcd8_label: "만성 장아메바증",
        },
        {
            id: "D00000041",
            medical_institution: "공통",
            local_label: "Amebic nondysenteric colitis",
            snomed_ct_code: "55023005",
            snomed_ct_label: "Amebic nondysenteric colitis (disorder)",
            kcd8_code: "A062",
            kcd8_label: "아메바성 비이질성 결장염",
        },
        {
            id: "D00000042",
            medical_institution: "공통",
            local_label: "Ameboma of intestine",
            snomed_ct_code: "3151000305105",
            snomed_ct_label: "Ameboma of intestine (disorder)",
            kcd8_code: "A063",
            kcd8_label: "장의 아메바종",
        },
        {
            id: "D00000043",
            medical_institution: "공통",
            local_label: "Amebic liver abscess",
            snomed_ct_code: "75119003",
            snomed_ct_label: "Amebic liver abscess (disorder)",
            kcd8_code: "A064",
            kcd8_label: "아메바성 간농양(K77.0*)",
        },
        {
            id: "D00000044",
            medical_institution: "공통",
            local_label: "Amebic lung abscess",
            snomed_ct_code: "65095005",
            snomed_ct_label: "Amebic lung abscess (disorder)",
            kcd8_code: "A065",
            kcd8_label: "아메바성 폐농양",
        },
        {
            id: "D00030030",
            medical_institution: "공통",
            local_label: "Amebic abscess of lung (and liver) with pneumonia",
            snomed_ct_code: "65095005",
            snomed_ct_label: "Amebic lung abscess (disorder)",
            kcd8_code: "A065",
            kcd8_label: "아메바성 폐농양",
        },
        {
            id: "D00000045",
            medical_institution: "공통",
            local_label: "Amebic brain abscess",
            snomed_ct_code: "27908001",
            snomed_ct_label: "Amebic brain abscess (disorder)",
            kcd8_code: "A066",
            kcd8_label: "아메바성 뇌농양(G07*)",
        },
        {
            id: "D00000046",
            medical_institution: "공통",
            local_label: "Amebiasis of skin",
            snomed_ct_code: "238449000",
            snomed_ct_label: "Amebiasis of skin (disorder)",
            kcd8_code: "A067",
            kcd8_label: "피부아메바증",
        },
        {
            id: "D00000047",
            medical_institution: "공통",
            local_label: "Amebic infection of other sites",
            snomed_ct_code: "111910009",
            snomed_ct_label: "Amebic infection (disorder)",
            kcd8_code: "A068",
            kcd8_label: "기타 부위의 아메바성 감염",
        },
        {
            id: "D00000049",
            medical_institution: "공통",
            local_label: "Free-living ameba infection",
            snomed_ct_code: "266169003",
            snomed_ct_label: "Free-living ameba infection (disorder)",
            kcd8_code: "A069",
            kcd8_label: "상세불명의 아메바증",
        },
        {
            id: "D00000048",
            medical_institution: "공통",
            local_label: "Amebiasis",
            snomed_ct_code: "111910009",
            snomed_ct_label: "Amebic infection (disorder)",
            kcd8_code: "A069",
            kcd8_label: "상세불명의 아메바증",
        },
        {
            id: "D00000050",
            medical_institution: "공통",
            local_label: "Balantidiasis",
            snomed_ct_code: "57725006",
            snomed_ct_label: "Balantidiasis (disorder)",
            kcd8_code: "A070",
            kcd8_label: "대장섬모충증",
        },
        {
            id: "D00000051",
            medical_institution: "공통",
            local_label: "Giardiasis",
            snomed_ct_code: "58265007",
            snomed_ct_label: "Giardiasis (disorder)",
            kcd8_code: "A071",
            kcd8_label: "편모충증[람블편모충증]",
        },
        {
            id: "D00000052",
            medical_institution: "공통",
            local_label: "Cryptosporidiosis",
            snomed_ct_code: "240370009",
            snomed_ct_label: "Cryptosporidiosis (disorder)",
            kcd8_code: "A072",
            kcd8_label: "와포자충증",
        },
        {
            id: "D00000053",
            medical_institution: "공통",
            local_label: "Coccidiosis",
            snomed_ct_code: "62005008",
            snomed_ct_label: "Coccidiosis (disorder)",
            kcd8_code: "A073",
            kcd8_label: "등포자충증",
        },
        {
            id: "D00000054",
            medical_institution: "공통",
            local_label: "Intestinal trichomoniasis",
            snomed_ct_code: "67915005",
            snomed_ct_label: "Intestinal trichomoniasis (disorder)",
            kcd8_code: "A078",
            kcd8_label: "기타 명시된 원충성 장질환",
        },
        {
            id: "D00000055",
            medical_institution: "공통",
            local_label: "Protozoal intestinal disease",
            snomed_ct_code: "89933001",
            snomed_ct_label: "Protozoal intestinal disease (disorder)",
            kcd8_code: "A079",
            kcd8_label: "상세불명의 원충성 장질환",
        },
        {
            id: "D00000056",
            medical_institution: "공통",
            local_label: "Rotavirus gastroenteritis",
            snomed_ct_code: "415822001",
            snomed_ct_label: "Viral gastroenteritis caused by Rotavirus (disorder)",
            kcd8_code: "A080",
            kcd8_label: "로타바이러스장염",
        },
        {
            id: "D00000057",
            medical_institution: "공통",
            local_label: "Norovirus gastroenteritis",
            snomed_ct_code: "24789006",
            snomed_ct_label: "Viral gastroenteritis caused by Norwalk-like agent (disorder)",
            kcd8_code: "A081",
            kcd8_label: "노로바이러스에 의한 급성 위장병증",
        },
        {
            id: "D00000058",
            medical_institution: "공통",
            local_label: "Adenovirus enteritis",
            snomed_ct_code: "70880006",
            snomed_ct_label: "Adenoviral enteritis (disorder)",
            kcd8_code: "A082",
            kcd8_label: "아데노바이러스장염",
        },
        {
            id: "D00022675",
            medical_institution: "공통",
            local_label: "Sapoviral gastroenteritis",
            snomed_ct_code: "1187631004",
            snomed_ct_label: "Viral gastroenteritis caused by Sapovirus (disorder)",
            kcd8_code: "A0830",
            kcd8_label: "사포바이러스 위장염",
        },
        {
            id: "D00022676",
            medical_institution: "공통",
            local_label: "Astroviral gastroenteritis",
            snomed_ct_code: "283876006",
            snomed_ct_label: "Astrovirus gastroenteritis (disorder)",
            kcd8_code: "A0831",
            kcd8_label: "아스트로바이러스 위장염",
        },
        {
            id: "D00022677",
            medical_institution: "공통",
            local_label: "Other viral enteritis",
            snomed_ct_code: "78420004",
            snomed_ct_label: "Inflammation of intestine caused by virus (disorder)",
            kcd8_code: "A0838",
            kcd8_label: "기타 바이러스장염",
        },
        {
            id: "D00000059",
            medical_institution: "공통",
            local_label: "Viral enteritis",
            snomed_ct_code: "78420004",
            snomed_ct_label: "Inflammation of intestine caused by virus (disorder)",
            kcd8_code: "A084",
            kcd8_label: "상세불명의 바이러스성 장감염",
        },
        {
            id: "D00000060",
            medical_institution: "공통",
            local_label: "Intestinal infection",
            snomed_ct_code: "266071000",
            snomed_ct_label: "Intestinal infectious disease (disorder)",
            kcd8_code: "A085",
            kcd8_label: "기타 명시된 장감염",
        },
        {
            id: "D00000065",
            medical_institution: "공통",
            local_label: "Infective diarrhea",
            snomed_ct_code: "19213003",
            snomed_ct_label: "Infectious diarrheal disease (disorder)",
            kcd8_code: "A090",
            kcd8_label: "감염성 기원의 기타 및 상세불명의 위장염 및 결장염",
        },
        {
            id: "D00000061",
            medical_institution: "공통",
            local_label: "Acute watery diarrhea",
            snomed_ct_code: "409966000",
            snomed_ct_label: "Acute diarrhea (disorder)",
            kcd8_code: "A090",
            kcd8_label: "감염성 기원의 기타 및 상세불명의 위장염 및 결장염",
        },
        {
            id: "D00000064",
            medical_institution: "공통",
            local_label: "Infectious enteritis",
            snomed_ct_code: "55184003",
            snomed_ct_label: "Infectious inflammation of intestine (disorder)",
            kcd8_code: "A090",
            kcd8_label: "감염성 기원의 기타 및 상세불명의 위장염 및 결장염",
        },
        {
            id: "D00000063",
            medical_institution: "공통",
            local_label: "Infectious colitis",
            snomed_ct_code: "39341005",
            snomed_ct_label: "Infectious colitis (disorder)",
            kcd8_code: "A090",
            kcd8_label: "감염성 기원의 기타 및 상세불명의 위장염 및 결장염",
        },
        {
            id: "D00022895",
            medical_institution: "공통",
            local_label: "Infective neonatal diarrhea",
            snomed_ct_code: "268850004",
            snomed_ct_label: "Neonatal diarrhea (disorder)",
            kcd8_code: "A090",
            kcd8_label: "감염성 기원의 기타 및 상세불명의 위장염 및 결장염",
        },
        {
            id: "D00000066",
            medical_institution: "공통",
            local_label: "Postinfectious diarrhea",
            snomed_ct_code: "62315008",
            snomed_ct_label: "Diarrhea (finding)",
            kcd8_code: "A090",
            kcd8_label: "감염성 기원의 기타 및 상세불명의 위장염 및 결장염",
        },
        {
            id: "D00000068",
            medical_institution: "공통",
            local_label: "Acute gastroenteritis",
            snomed_ct_code: "69776003",
            snomed_ct_label: "Acute gastroenteritis (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00000075",
            medical_institution: "공통",
            local_label: "Ileitis",
            snomed_ct_code: "52457000",
            snomed_ct_label: "Ileitis (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00000072",
            medical_institution: "공통",
            local_label: "Enterocolitis",
            snomed_ct_code: "43752006",
            snomed_ct_label: "Inflammation of small intestine and colon (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00000074",
            medical_institution: "공통",
            local_label: "Gastroenteritis and colitis of unspecified origin",
            snomed_ct_code: "25374005",
            snomed_ct_label: "Inflammation of stomach and intestine (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00000077",
            medical_institution: "공통",
            local_label: "Neutropenic enterocolitis",
            snomed_ct_code: "45451000305106",
            snomed_ct_label: "Neutropenic colitis of small intestine and colon (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00000062",
            medical_institution: "공통",
            local_label: "Dysentery",
            snomed_ct_code: "46799006",
            snomed_ct_label: "Dysenteric diarrhea (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00000070",
            medical_institution: "공통",
            local_label: "Diarrhea",
            snomed_ct_code: "62315008",
            snomed_ct_label: "Diarrhea (finding)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00000067",
            medical_institution: "공통",
            local_label: "Acute enteritis",
            snomed_ct_code: "64613007",
            snomed_ct_label: "Inflammation of small intestine (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00000076",
            medical_institution: "공통",
            local_label: "Jejunitis",
            snomed_ct_code: "80805005",
            snomed_ct_label: "Jejunitis (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00022894",
            medical_institution: "공통",
            local_label: "Neonatal diarrhea",
            snomed_ct_code: "268850004",
            snomed_ct_label: "Neonatal diarrhea (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00000071",
            medical_institution: "공통",
            local_label: "Enteritis",
            snomed_ct_code: "1187638005",
            snomed_ct_label: "Inflammation of intestine (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00000069",
            medical_institution: "공통",
            local_label: "Colitis",
            snomed_ct_code: "64226004",
            snomed_ct_label: "Colitis (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00000073",
            medical_institution: "공통",
            local_label: "Gastroenteritis",
            snomed_ct_code: "12463005",
            snomed_ct_label: "Infectious gastroenteritis (disorder)",
            kcd8_code: "A099",
            kcd8_label: "상세불명 기원의 위장염 및 결장염",
        },
        {
            id: "D00030031",
            medical_institution: "공통",
            local_label: "Pulmonary tuberculosis, bacteriologically confirmed",
            snomed_ct_code: "154283005",
            snomed_ct_label: "Pulmonary tuberculosis (disorder)",
            kcd8_code: "A150",
            kcd8_label: "배양 유무에 관계없이 가래 현미경 검사로 확인된 폐결핵",
        },
        {
            id: "D00000078",
            medical_institution: "공통",
            local_label: "Pulmonary tuberculosis, confirmed by sputum microscopy with or without culture",
            snomed_ct_code: "186193001",
            snomed_ct_label: "Tuberculosis of lung, confirmed by sputum microscopy with or without culture (disorder)",
            kcd8_code: "A150",
            kcd8_label: "배양 유무에 관계없이 가래 현미경 검사로 확인된 폐결핵",
        },
        {
            id: "D00000079",
            medical_institution: "공통",
            local_label: "Pulmonary tuberculosis, confirmed by culture only",
            snomed_ct_code: "186194007",
            snomed_ct_label: "Tuberculosis of lung, confirmed by culture only (disorder)",
            kcd8_code: "A151",
            kcd8_label: "배양만으로 확인된 폐결핵",
        },
        {
            id: "D00000080",
            medical_institution: "공통",
            local_label: "Pulmonary tuberculoma, confirmed by histology",
            snomed_ct_code: "186195008",
            snomed_ct_label: "Tuberculosis of lung, confirmed histologically (disorder)",
            kcd8_code: "A152",
            kcd8_label: "조직학적으로 확인된 폐결핵",
        },
        {
            id: "D00000081",
            medical_institution: "공통",
            local_label: "Pulmonary tuberculosis, confirmed by histology",
            snomed_ct_code: "186195008",
            snomed_ct_label: "Tuberculosis of lung, confirmed histologically (disorder)",
            kcd8_code: "A152",
            kcd8_label: "조직학적으로 확인된 폐결핵",
        },
        {
            id: "D00000082",
            medical_institution: "공통",
            local_label: "Fibrocalcified pulmonary tuberculosis, confirmed by unspecified means",
            snomed_ct_code: "154283005",
            snomed_ct_label: "Pulmonary tuberculosis (disorder)",
            kcd8_code: "A153",
            kcd8_label: "상세불명의 수단으로 확인된 폐결핵",
        },
        {
            id: "D00000083",
            medical_institution: "공통",
            local_label: "Pulmonary tuberculoma, confirmed by unspecified means",
            snomed_ct_code: "154283005",
            snomed_ct_label: "Pulmonary tuberculosis (disorder)",
            kcd8_code: "A153",
            kcd8_label: "상세불명의 수단으로 확인된 폐결핵",
        },
        {
            id: "D00000084",
            medical_institution: "공통",
            local_label: "Pulmonary tuberculosis, confirmed by unspecified means",
            snomed_ct_code: "154283005",
            snomed_ct_label: "Pulmonary tuberculosis (disorder)",
            kcd8_code: "A153",
            kcd8_label: "상세불명의 수단으로 확인된 폐결핵",
        },
        {
            id: "D00000085",
            medical_institution: "공통",
            local_label: "Tuberculosis of intrathoracic lymph nodes, confirmed by bacteriology and histology",
            snomed_ct_code: "78436002",
            snomed_ct_label: "Tuberculosis of intrathoracic lymph nodes (disorder)",
            kcd8_code: "A154",
            kcd8_label: "세균학적 및 조직학적으로 확인된 흉곽내림프절의 결핵",
        },
        {
            id: "D00000086",
            medical_institution: "공통",
            local_label: "Active caseating endobronchial tuberculosis confirmed by bacteriology and histology",
            snomed_ct_code: "25629007",
            snomed_ct_label: "Acute tuberculosis (disorder)",
            kcd8_code: "A155",
            kcd8_label: "세균학적 및 조직학적으로 확인된 후두, 기관 및 기관지의 결핵",
        },
        {
            id: "D00000088",
            medical_institution: "공통",
            local_label: "Fibrostenotic type endobronchial tuberculosis confirmed by bacteriology and histology",
            snomed_ct_code: "186199002",
            snomed_ct_label: "Tuberculosis of larynx, trachea and bronchus, confirmed bacteriologically and histologically (disorder)",
            kcd8_code: "A155",
            kcd8_label: "세균학적 및 조직학적으로 확인된 후두, 기관 및 기관지의 결핵",
        },
        {
            id: "D00000089",
            medical_institution: "공통",
            local_label: "Laryngeal tuberculosis,confirmed by bacteriology and histology",
            snomed_ct_code: "186199002",
            snomed_ct_label: "Tuberculosis of larynx, trachea and bronchus, confirmed bacteriologically and histologically (disorder)",
            kcd8_code: "A155",
            kcd8_label: "세균학적 및 조직학적으로 확인된 후두, 기관 및 기관지의 결핵",
        },
        {
            id: "D00000090",
            medical_institution: "공통",
            local_label: "Tracheal tuberculosis confirmed by bacteriology and histology",
            snomed_ct_code: "186199002",
            snomed_ct_label: "Tuberculosis of larynx, trachea and bronchus, confirmed bacteriologically and histologically (disorder)",
            kcd8_code: "A155",
            kcd8_label: "세균학적 및 조직학적으로 확인된 후두, 기관 및 기관지의 결핵",
        },
        {
            id: "D00000087",
            medical_institution: "공통",
            local_label: "Endobronchial tuberculosis, confirmed by bacteriology and histology",
            snomed_ct_code: "186199002",
            snomed_ct_label: "Tuberculosis of larynx, trachea and bronchus, confirmed bacteriologically and histologically (disorder)",
            kcd8_code: "A155",
            kcd8_label: "세균학적 및 조직학적으로 확인된 후두, 기관 및 기관지의 결핵",
        },
        {
            id: "D00000091",
            medical_institution: "공통",
            local_label: "Tuberculous pleurisy, confirmed by bacteriology and histology",
            snomed_ct_code: "186200004",
            snomed_ct_label: "Tuberculous pleurisy, confirmed bacteriologically and histologically (disorder)",
            kcd8_code: "A156",
            kcd8_label: "세균학적 및 조직학적으로 확인된 결핵성 흉막염",
        },
        {
            id: "D00000092",
            medical_institution: "공통",
            local_label: "Primary respiratory tuberculosis, confirmed by bacteriology and histology",
            snomed_ct_code: "186201000",
            snomed_ct_label: "Primary respiratory tuberculosis, confirmed bacteriologically and histologically (disorder)",
            kcd8_code: "A157",
            kcd8_label: "세균학적 및 조직학적으로 확인된 일차호흡기결핵",
        },
    ]
}